define([
    {
		title:"4 wives",
		artist:"筷子兄弟",
		mp3:"sound/4wives.mp3",
		lrc:"4wives.lrc",
		poster:"/album/4.jpg"
	},
	{
		title:"海阔天空",
		artist:"Beyond",
		mp3:"sound/haiKuoTianKong.mp3",
		lrc:"haiKuoTianKong.lrc",
		poster:"/album/haiKuoTianKong.jpg"
	},
	{
		title:"晓梦蝶",
		artist:"群星",
		mp3:"sound/xiaoMengdie.mp3",
		lrc:"",
		poster:"/album/minLeFoYun.jpg"
	},
	{
		title:"幽兰",
		artist:"群星",
		mp3:"sound/youLan.mp3",
		lrc:"",
		poster:"/album/minLeFoYun.jpg"
	}
]);
