define([
    {
		title:"4 wives",
		artist:"筷子兄弟",
		mp3:"sound/4wives.mp3",
		lrc:"4wives.lrc",
		poster:"/album/4.jpg"
	},
	{
		title:"小苹果",
		artist:"筷子兄弟",
		mp3:"sound/littleApple.mp3",
		lrc:"littleApple.lrc",
		poster:"/album/littleApple.jpg"
	},
	{
		title:"我很快乐",
		artist:"刘惜君",
		mp3:"sound/woHenKuaiLe.mp3",
		lrc:"woHenKuaiLe.lrc",
		poster:"/album/woHenKuaiLe.jpg"
	},
	{
		title:"偏爱",
		artist:"张芸京",
		mp3:"sound/pianAi.mp3",
		lrc:"pianAi.lrc",
		poster:"/album/pianAi.jpg"
	},
	{
		title:"雨一直下",
		artist:"张宇",
		mp3:"sound/yuYiZhiXia.mp3",
		lrc:"yuYiZhiXia.lrc",
		poster:"/album/yuYiZhiXia.jpg"
	},
	{
		title:"来生缘/一起走过的日子",
		artist:"刘德华",
		mp3:"sound/laiShengYuan.mp3",
		lrc:"laiShengYuan.lrc",
		poster:"/album/laiShengYuan.jpg"
	},
	/*{
		title:"来生缘1/超高音质",
		artist:"刘德华1",
		mp3:"sound/CGlaiShengYuan.mp3",
		lrc:"laiShengYuan.lrc",
		poster:"/album/woHenKuaiLe.jpg"
	},*/
	{
		title:"怒放的生命",
		artist:"汪峰",
		mp3:"sound/nuFangDeShengMing.mp3",
		lrc:"nuFangDeShengMing.lrc",
		poster:"/album/nuFangDeShengMing.jpg"
	},
	{
		title:"水手",
		artist:"郑智化",
		mp3:"sound/shuiShou.mp3",
		lrc:"shuiShou.lrc",
		poster:"/album/shuiShou.jpg"
	},
	{
		title:"把悲伤留给自己",
		artist:"陈升",
		mp3:"sound/baBeiShangLiuGeiZiJi.mp3",
		lrc:"baBeiShangLiuGeiZiJi.lrc",
		poster:"/album/baBeiShangLiuGeiZiJi.jpg"
	},
	{
		title:"海阔天空",
		artist:"Beyond",
		mp3:"sound/haiKuoTianKong.mp3",
		lrc:"haiKuoTianKong.lrc",
		poster:"/album/haiKuoTianKong.jpg"
	},
	{
		title:"晓梦蝶",
		artist:"群星",
		mp3:"sound/xiaoMengdie.mp3",
		lrc:"",
		poster:"/album/minLeFoYun.jpg"
	},
	{
		title:"幽兰",
		artist:"群星",
		mp3:"sound/youLan.mp3",
		lrc:"",
		poster:"/album/minLeFoYun.jpg"
	}
]);
